# Generated by Django 5.0.4 on 2024-05-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_meal_date_alter_mealcategory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calorie_sum',
            field=models.FloatField(default=0, null=True),
        ),
    ]
