# Generated by Django 5.0.4 on 2024-05-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('Похудение', 'Loss'), ('Поддержание веса', 'Maintaint'), ('Набор массы', 'Gain')], default='Поддержание веса', max_length=16),
        ),
    ]
