# Generated by Django 5.0.4 on 2024-05-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'М'), ('Женский', 'Ж')], default=None, max_length=7, null=True),
        ),
    ]
