# Generated by Django 5.0.4 on 2024-05-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_calorie_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('Loss', 'Похудение'), ('Main', 'Поддержание веса'), ('Gain', 'Набор массы')], default='Main', max_length=16),
        ),
    ]
