# Generated by Django 5.0.4 on 2024-05-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfood',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
