# Generated by Django 5.0.4 on 2024-05-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_mealfood_calorie_alter_food_calorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='calorie',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
